language: ruby

services:
  - postgresql

script:
  - make test

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: "9.6"

dist: trusty
sudo: required
